#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd
# Displays username, user id and Home directory path for the user

while LISTFILE='' read -r LINE
do
	echo "$LINE" | cut -d ":" -f1,4,7
done < /etc/passwd
