#!/usr/bin/env bash
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

count=10
while [ $count -gt 0 ]
do
	if [ $count -eq 7 ]
	then
		echo "bad luck"
	elif [ $count -eq 3 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$(( count - 1 ))
done
